""" Organisations and their URLs
"""
ORGANISATIONS = {
    "http://www.100resilientcities.org": "100 Resilient Cities",
    "http://www.acri-st.fr/English/index.html": "Earth Observation - Environment (ACRI-ST)",
    "http://agage.eas.gatech.edu": "Advanced Global Atmospheric Gases Experiment (AGAGE)",
    "https://ageconsearch.umn.edu/pages/?page=about": "AgEcon Search",
    "http://www2.ademe.fr/servlet/getDoc?id=11433&m=3&cid=96": "Agence de l'Environnement et de la Maitrise de l'Energie - ADEME",
    "http://www.aemet.es/en/portada": "Agencia Estatal de Meteorología (AEMET)",
    "http://www.qualar.org/": "Agência Portuguesa do Ambiente",
    "http://www.plan-og-bygningsetaten.oslo.kommune.no/information_in_english/": "Agency for Planning and Building Services, city of Oslo",
    "http://acm.eionet.europa.eu": "European Topic Centre on Air pollution and Climate change mitigation (ETC/ACM)",
    "http://www.environnement.public.lu/index.html": "Air Quality Luxembourg",
    "http://www.umweltbundesamt.at/": "Air Quality Network Austria",
    "http://www.uni-klu.ac.at/main/inhalt/1.htm": "Alpen Adria Universität Klagenfurt (Austria)",
    "http://www.alpconv.org/home/index_en": "ALPINE CONVENTION",
    "http://www.alparc.org": "Alpine Network of Protected Areas (ALPARC)",
    "http://www.alterra.wur.nl/UK/": "ALTERRA",
    "http://amap.nrpa.no/index.htm": "AMAP International Datacentre for Radioactivity",
    "https://amber.international/": "AMBER Consortium",
    "http://www.ambienteitalia.it/": "Ambiente Italia S.r.l. - Research Institute",
    "http://www.aaas.org/": "American Association for the Advancement of Science (AAAS)",
    "https://www.adci.com/": "American Digital Cartography Inc (ADCi)",
    "http://sites.agu.org/": "American Geophysical Union (AGU)",
    "http://www.aire.ad/": "Departament de Medi Ambient, Govern d'Andorra",
    "http://www.acecrc.org.au/": "Antarctic Climate & Ecosystems Cooperative Research Centre",
    "http://www.apice-project.eu/content.php?ID1=5&ID=5&lang=ENG": "APICE",
    "http://gamta.lt/cms/index?lang=lt": "Aplinkos apsaugos agentūra",
    "http://www.ibimet.cnr.it/programmi/Pcase/index.htm": "Applied Meteorology Foundation (FMA)",
    "http://www.apl.washington.edu": "Applied Physics Laboratory (APL-UW)",
    "http://www.corpi.ku.lt/databases/index.php/aquanis": "Klaipeda university",
    "http://www.archelon.gr": "ARCHELON The Sea Turtle Protection Society of Greece",
    "http://www.arctic-council.org/index.php/en/": "Arctic Council",
    "http://www.amap.no/": "Arctic Monitoring and Assessment Programme (AMAP)",
    "http://www.argo.ucsd.edu/index.html": "Argo",
    "http://www.aea.be": "Association of European Airlines (AEA)",
    "http://www.aslo.org/index.html": "Association for the Sciences of Limnology and Oceanography (ASLO)",
    "http://www.atmospheric-chemistry-and-physics.net/": "Atmospheric Chemistry and Physics (ACP)",
    "http://www.mambiente.munimadrid.es/opencms/opencms/calaire": "Ayuntamiento de Madrid",
    "https://www.azti.es/en/": "AZTI",
    "http://www.boos.org": "Baltic Operational Oceanographic System (BOOS)",
    "https://ventes-produits-phytopharmaceutiques.eaufrance.fr/": "Banque Nationale des Ventes distributeurs (BNV-d)",
    "http://www.barcelonaenergia.cat/homeeng.htm": "Barcelona Energy Agency",
    "https://www.isglobal.org/en": "Barcelona Institute for Global Health (ISGlobal)",
    "https://www.bsc.es/": "Barcelona Supercomputing Center (BSC)",
    "http://www.basel.int/": "Basel Convention",
    "http://www.benthis.eu/en/benthis.htm": "BENTHIS",
    "http://berkeleyearth.org/": "Berkeley Earth",
    "http://www.biois.com/en/": "Bio Intelligence",
    "http://www.cpb.bio.ic.ac.uk/BIODEPTH": "Centre for Population Biology (CPB)",
    "http://www.biodiversitymonitoring.ch/english/aktuell/portal.php": "Biodiversity Monitoring Switzerland (BDM)",
    "http://www.bioversityinternational.org": "Bioversity International",
    "http://www.birdlife.net": "BirdLife International",
    "http://www.bu.edu": "Boston University (BU)",
    "http://www.bgs.ac.uk/home.html": "British Geological Survey",
    "http://www.bp.com": "British Petroleum (BP)",
    "http://www.brookings.edu/": "Brookings Institution",
    "http://bpie.eu/": "Buildings Performance Institute Europe (BPIE)",
    "http://www.bsh.de/de/index.jsp": "Bundesamt für Seeschifffahrt und Hydrographie (BSH)",
    "https://www.bfn.de/0324_auenzustand.html": "The German Federal Agency for Nature Conservation (Bundesamt für Naturschutz)",
    "http://www.lebensministerium.at/": "Bundesministerium für Land- und Forstwirtschaft, Umwelt und Wasserwirtschaft (BMLFUW)",
    "http://www.brg.prd.fr/index_an.php": "Bureau des Ressources Genetiques (BRG)",
    "http://www.bc-europe.eu": "Butterfly Conservation Europe (BCE)",
    "http://www.c40.org": "C40",
    "http://www.caff.is": "Conservation of Arctic Flora and Fauna (CAFF)",
    "https://librairie.ademe.fr/": "Caractérisation des effets rebond induits par le télétravail - Greenworking and ADEME",
    "http://www.carboeurope.org": "CarboEurope-IP",
    "http://cdiac.ornl.gov/": "Carbon Dioxide Information and Analysis Center (CDIAC)",
    "https://www.cdproject.net/en-US/Pages/HomePage.aspx": "Carbon Disclosure Project (CDP)",
    "http://carmen.naturefrance.fr/": "Carmen",
    "http://www.carpatclim-eu.org/pages/home/": "CarpatCLIM",
    "http://www.carpivia.eu/": "Carpivia",
    "http://www.castillalamancha.es/": "Castilla-La Mancha, Spain",
    "http://wge-cce.org/": "Coordination Centre for Effects (CCE)",
    "https://data.cdp.net/": "CDP Cities, States and Regions Open Data Portal",
    "http://www.ceeweb.org/": "CEEweb for Biodiversity",
    "http://www.creaf.uab.es": "Center for Ecological Research and Forestry Applications (CREAF)",
    "https://www.gtap.agecon.purdue.edu/": "Center for Global Trade Analysis Department of Agricultural Economics Purdue University",
    "http://www.npolar.no": "Center for Ice Climate and Ecosystems (ICE)",
    "http://www.nonproliferation.org/": "Center for Nonproliferation Studies (CNS)",
    "http://www.citl.org/": "Center of Information Technology Leadership (CITL)",
    "http://oekoklimatologie.wzw.tum.de/": "Center of Life and Food Sciences Weihenstephan (WZW TUM)",
    "http://www.dzs.hr/default_e.htm": "Croatian Bureau of Statistics (CBS)",
    "http://www.zamg.ac.at": "Central Institute for Meteorology and Geodynamics (ZAMG)",
    "https://www.cia.gov/index.html": "Central Intelligence Agency (CIA)",
    "http://stat.gov.pl/en/": "Central Statistical Office of Poland",
    "http://www.cso.ie": "Central statistics office, Ireland (CSO)",
    "http://www.ceh.ac.uk": "Centre for Ecology and Hydrology (CEH)",
    "http://www.cefas.defra.gov.uk/": "Centre for Environment, Fisheries & Aquaculture Science (CEFAS)",
    "http://www.mnhn.fr/mnhn/crbpo": "Centre for research in biology and bird population (CRBPO)",
    "http://www.cred.be/": "Centre for Research on the Epidemiology of Disasters (CRED)",
    "http://www.eec.univ-montp2.fr/": "Centre national de la recherche scientifique (CNRS)",
    "http://www.ceip.at/": "Centre on Emission Inventories and Projections (CEIP)",
    "http://www.genomicsnetwork.ac.uk/cesagen": "CESAGEN, University of Lancaster",
    "http://www.cgd.ucar.edu/cas": "CGD's Climate Analysis Section",
    "http://www.citypopulation.de/": "City Population",
    "http://cleanairinitiative.org/": "Clean Air Initiative for Asian Cities (CAI-Asia)",
    "http://www.ccrc.unsw.edu.au/": "Climate Change Research Centre",
    "http://www.climatecost.cc/": "Climate Cost",
    "http://www.euro-cordex.net/": "EURO-CORDEX",
    "http://www.climwatadapt.eu/": "ClimWatAdapt Kassen University",
    "http://cmip-pcmdi.llnl.gov/": "CMIP coupled model intercomparison project",
    "http://www.irpi.cnr.it/": "Istituto di Ricerca per la Protezione Idrogeologica del Consiglio Nazionale delle Ricerche (CNR IRPI)",
    "http://www.cls.fr/welcome_en.html": "Collecte Localisation Satellite (CLS)",
    "http://www.ues.pku.edu.cn/english": "College of Urban and Environmental Sciences, Peking University, Beijing, China",
    "http://www.bartholomewmaps.com": "Collins Bartholomew",
    "http://www.csiro.au/": "Commonwealth Scientific and Industrial Research Organisation (CSIRO)",
    "http://www.compactofmayors.org/": "Compact of Mayors",
    "http://www.compendiumvoordeleefomgeving.nl/": "Compendium voor de Leefomgeving",
    "http://www.compendiumvoordeleefomgeving.nl/contact/": "Entity to delete",
    "http://gpe.concordia.ca/": "Concordia University - Geography, Planning and Environment",
    "http://www.cime.es": "Conseil Insular de Menorca",
    "http://www.juntadeandalucia.es/index.html": "Consejería de Agricultura, Pesca y Medio Ambiente de la Junta de Andalucía",
    "http://www.medioambientecantabria.com/": "Consejero de Medio Ambiente, Ordenación del Territorio y Urbanismo, Gobierno de Cantabria",
    "http://www.cmati.xunta.es/portada": "Consellería de Medio Ambiente, Xunta de Galicia",
    "http://www.cbd.int": "Convention on Biological Diversity",
    "http://www.unece.org/env/lrtap/multi_h1.htm": "Convention on Long-range Transboundary Air Pollution (LTRAP)",
    "http://www.cri.dk": "Copenhagen Resource Institute (CRI)",
    "https://atmosphere.copernicus.eu/": "Copernicus Atmosphere Monitoring Service (CAMS)",
    "http://climate.copernicus.eu/": "Copernicus Climate Change Service (C3S)",
    "https://marine.copernicus.eu/": "Copernicus CMEMS",
    "http://land.copernicus.eu/": "Copernicus Land Monitoring Services",
    "http://marine.copernicus.eu/": "Copernicus Marine Environment Monitoring Service",
    "http://www.coe.int": "Council of Europe (CoE)",
    "http://www.landis.org.uk/gateway/ooi/welcome.cfm": "Cranfield University (National Soil Resources Institute)",
    "http://www.emdat.be/": "CRED, Université Catholique de Louvain - Brussels",
    "http://www.azo.hr/English": "Croatian Environment Agency (AZO)",
    "http://www.crue-eranet.net/": "CRUE ERA-Net consortium",
    "http://www.cruiseeurope.com/": "Cruise Europe",
    "http://www.cryosphere.ch/englindex.html": "Cryospheric Commission of the Swiss Academy of Sciences (SCNAT)",
    "http://portal.chmi.cz/": "Czech Hydrometeorological Institute (CHMI)",
    "http://www.chmi.cz/portal/dt?portal_lang=en&menu=JSPTabContainer/P1_0_Home": "Entity to delete",
    "https://www.mzp.cz/en": "Ministry of the Environment of the Czechia",
    "http://www.sydos.cz/en/yearbook-2006/yearbook/htm_uk/uk06_514000.html": "Czech ministry of transport",
    "http://www.birdlife.cz/index.php?a=cat.53": "Czech Society for Ornithology",
    "http://www.czso.cz/eng/redakce.nsf/i/home": "Czech Statistical Office",
    "http://dce.au.dk/en/": "Danish Centre for Environment and Energy",
    "http://dce.au.dk/": "Danish Centre for Environment and Energy",
    "http://eng.kyst.dk/": "Danish Coastal Authorities",
    "http://www.dmi.dk/eng/index/forecasts.htm": "Danish Meteorological Institute (DMI)",
    "http://www.wasteandresources.dk": "Danish Topic Centre on Waste and Resources",
    "http://www.ddni.ro/index.php?page_id=84&siteSection=1&sectionTitle=Home": "Danube Delta National Institute for Research and Development (DDNI)",
    "http://floodobservatory.colorado.edu/": "Dartmouth Flood Observatory",
    "http://www.dcmr.nl/en/index.html": "DCMR Environmental Protection Agency",
    "http://www.europe-aliens.org/": "Delivering Alien Invasive Species Inventories for Europe (DAISIE)",
    "https://www.deltares.nl/en/": "Deltares",
    "http://www.navarra.es/home_es/Gobierno+de+Navarra/Organigrama/Los+departamentos/Desarrollo+Rural+y+Medio+Ambiente/": "Departamento de Desarrollo Rural y Medio Ambiente de Navarra",
    "http://www.ingurumena.ejgv.euskadi.net/r49-home/es": "Departamento de Medio Ambiente, Planificación Territorial, Agricultura y Pesca, Gobierno Vasco",
    "http://www.agriculture.gov.ie/": "Department of Agriculture and Food, Ireland",
    "http://www.airquality.dli.mlsi.gov.cy/": "Department of Labour Inspection - Ministry of Labour and Social Insurance, Cyprus",
    "https://www.gov.ie/en/": "Department of Public Expenditure and Reform, Ireland",
    "http://dismed.eionet.europa.eu": "Desertification Information System for the Mediterranean (DIS/MED)",
    "http://ec.europa.eu/agriculture/index_en.htm": "Directorate-General for Agriculture and Rural Development (DG-AGRI)",
    "http://ec.europa.eu/energy/": "Directorate-General Energy (DG-ENER)",
    "http://www.diegeographen.ch": "Die Geographen Schwick + Spichtig",
    "https://www.wbcsd.org/": "World Business Council For Sustainable Development (WBCSD)",
    "http://digital.csic.es/": "DIGITAL.CSIC",
    "http://ec.europa.eu/enterprise/index_en.htm": "Directorate-General Enterprise and Industry (DG-ENTR)",
    "http://ec.europa.eu/dgs/clima/mission/index_en.htm": "Directorate-General for Climate Action (DG-CLIMA)",
    "http://ec.europa.eu/economy_finance/index_en.htm": "Directorate-General for Economic and Financial Affairs (DG ECFIN)",
    "http://ec.europa.eu/dgs/energy_transport/index_en.html": "Directorate-General for Energy and Transport",
    "http://ec.europa.eu/dgs/environment/index_en.htm": "Directorate-General for Environment (DG ENV)",
    "http://ec.europa.eu/transport/index_en.htm": "Directorate General for Mobility and Transport (DG MOVE)",
    "http://ec.europa.eu/dgs/regional_policy/index_en.htm": "Directorate-General for Regional Policy",
    "https://ec.europa.eu/taxation_customs/index_en": "Directorate-General for Taxation and Customs Union",
    "http://www.europarl.europa.eu/aboutparliament/en/00d7a6c2b2/Secretariat.html?tab=eParliament_secretariat_dgipol": "Directorate-General Internal Policies of the Union",
    "https://discodata.eea.europa.eu/": "Discodata",
    "http://www.diva-gis.org/": "DIVA-GIS",
    "http://www.dongenergy.com": "Dong energy",
    "http://www.p2pays.org/ref/07/06250.pdf": "Doorn M.R.J and M.A. Barlaz (1995)",
    "http://www.djindexes.com/": "Dow Jones Indexes",
    "http://www.space.dtu.dk/": "DTU Space",
    "https://www.dunelm.org.uk/home": "Durham University",
    "http://edc.usgs.gov/": "Earth Resources Observation and Science (EROS) Center",
    "http://www.eaufrance.fr/": "Eaufrance",
    "http://www.ecn.nl/nl/": "Energy research Centre of the Netherlands (ECN)",
    "http://www.eco-innovation.eu/": "Eco-innovation observatory (EIO)",
    "http://www.ecologic.eu/": "Ecologic Institute",
    "http://www.eia.doe.gov/": "US Energy Information Administration (EIA)",
    "http://nfp-bg.eionet.europa.eu/": "EIONET National Focal Point - Bulgaria",
    "http://www.eionet.europa.eu/ldap-roles/?role_id=eionet-nrc": "Eionet NRC Soil",
    "https://www.elsevier.com/": "Elsevier",
    "http://www.emep.int": "EMEP",
    "http://www.emisia.com/": "EMISIA",
    "http://emisia.com/": "EMISIA",
    "http://www.enerdata.net/": "Enerdata Research Service",
    "http://www.nea.fr/": "Nuclear Energy Agency (NEA)",
    "https://www.sciencedirect.com/journal/energy-strategy-reviews": "Energy Strategy Reviews",
    "http://ensembles-eu.metoffice.com/": "ENSEMBLE FP6 project",
    "https://www.umweltbundesamt.at/": "Environment Agency Austria (Umwelt Bundesamt)",
    "http://www.ec.gc.ca": "Environment Canada",
    "http://www.eci.ox.ac.uk/": "Environmental Change Institute, Oxford University Centre for the Environment",
    "http://www.epa.ie/": "Environmental Protection Agency - Ireland",
    "http://www.fzoeu.hr/hrv/index.asp": "Environmental protection and energy efficiency Fund, Croatia",
    "http://tef.elte.hu/": "Eötvös Loránd University, Institute of geography and earth sciences",
    "https://www.esma.europa.eu/": "ESMA",
    "http://www.esri.com": "ESRI",
    "http://www.eea.europa.eu/data-and-maps/data-providers-and-partners/portal_factory/Organisation/organisation.2012-10-16.9303035723/edit": "Estonian Environmental Information Centre (EEIC)",
    "http://www.klab.ee/": "Eesti Keskkonnauuringute Keskus - Estonian Environmental Research Centre (EKUK)",
    "http://www.emu.ee/": "Estonian University of Life Sciences",
    "https://www.eionet.europa.eu/etcs/etc-ce": "ETC Circular economy and resource use (ETC CE)",
    "https://www.eionet.europa.eu/etcs/etc-cm": "ETC Climate change mitigation (ETC/CM)",
    "http://www.iac.ethz.ch/": "ETH Zürich - Institute for Atmospheric and Climate Science",
    "https://ethz.ch/": "ETH Zürich",
    "http://osisaf.met.no": "EUMETSAT OSI SAF",
    "https://visualisation.osha.europa.eu/osh-barometer/": "EUOSHA (OSH Barometer)",
    "http://eur-lex.europa.eu/homepage.html?locale=en": "EUR-Lex",
    "http://www.eurac.edu/index": "EURAC Research",
    "http://www.cmcc.it/": "Euro-Mediterranean Centre on Climate Change (CMMC)",
    "https://www.eurofound.europa.eu/": "Eurofound",
    "http://www.eurogeographics.org/home": "EuroGeographics",
    "http://www.eurogeosurveys.org/": "EuroGeoSurveys",
    "https://www.euronatur.org/": "EuroNatur",
    "http://www.europarc.org": "Europarc Federation",
    "http://ims.eionet.europa.eu": "Europe-wide questionnaire responses",
    "https://eafo.eu/": "European Alternative Fuels Observatory (EAFO)",
    "http://www.eppo.int/": "European and Mediterranean Plan Protection Organization (EPPO)",
    "http://www.acea.be": "European Automobile Manufactors Association (ACEA)",
    "http://www.ebcc.info": "European Bird Census Council  (EBCC)",
    "https://butterfly-monitoring.net/": "Assessing Butterflies in Europe (ABLE)",
    "http://www.eurocare-bonn.de": "European Centre for Agricultural, Regional and Environmental Policy Research - EUROCARE GmbH",
    "http://www.ecmwf.int": "European Centre for Medium-Range Weather Forecasts (ECMWF)",
    "http://www.ecnc.nl/index.html": "European Centre for Nature Conservation",
    "http://ecdc.europa.eu/en": "European Centre for Disease Prevention and Control (ECDC)",
    "http://eca.knmi.nl/": "European Climate Assessment & Dataset",
    "http://www.ecx.eu/": "European Climate Exchange (ECX)",
    "http://ec.europa.eu/index_en.htm": "European Commission",
    "http://ec.europa.eu": "European Commission",
    "http://ec.europa.eu/euratom/index.html": "Euratom Supply Agency (ESA)",
    "http://www.consilium.europa.eu/en/home/": "European Council",
    "http://www.consilium.europa.eu/en/european-council/": "European Council",
    "https://www.eex.com": "European Energy Exchange AG (EEX)",
    "https://www.eex.com/en/": "European Energy Exchange AG (EEX)",
    "http://www.eea.europa.eu": "European Environment Agency (EEA)",
    "http://www.transportenvironment.org/": "European Federation for Transport and Environment",
    "https://www.efsa.europa.eu/en": "European Food Safety Authority (EFSA)",
    "https://effis.jrc.ec.europa.eu/": "European Forest Fire Information System (EFFIS)",
    "http://www.efi.int": "European Forest Institute (EFI)",
    "https://www.efta.int/": "European Free Trade Association (EFTA)",
    "http://www.efama.org/SitePages/Home.aspx": "European Fund and Asset Management Association (EFAMA)",
    "http://www.icm.csic.es/bio/projects/strategy": "European Initiative on Harmful Algal Blooms",
    "http://www.emodnet.eu/": "European Marine Observation and Data Network (EMODnet)",
    "http://www.emsa.europa.eu/": "European Maritime Safety Agency (EMSA)",
    "https://www.ema.europa.eu/en": "European Medicines Agency",
    "http://www.emsc-csem.org": "European-Mediterranean Seismological Centre",
    "http://www.emta.com/?lang=en": "European Metropolitan Transport Authorities (EMTA)",
    "http://www.espon.eu/main/": "European Observation Network for Territorial Development and Cohesion (ESPON)",
    "https://www.epo.org/index.html": "European Patent Office (EPO)",
    "http://www.epomm.eu/index.php": "European Platform on Mobility Management (EPOMM)",
    "http://www.nine-esf.org/index.html": "European science foundation",
    "http://eusoils.jrc.ec.europa.eu/resource-type/datasets": "EUROPEAN SOIL DATA CENTRE (ESDAC)",
    "http://www.esa.int/esaCP/": "European Space Agency (ESA)",
    "https://www.eionet.europa.eu/etcs/etc-cme": "European Topic Centre on Climate Change Mitigation and Energy (ETC/CME)",
    "https://www.eionet.europa.eu/etcs/etc-he": "European Topic Centre Human health and the environment (ETC HE)",
    "https://www.eionet.europa.eu/etcs/etc-atni": "European Topic Centre on Air Pollution, Transport, Noise and Industrial Pollution (ETC/ATNI)",
    "http://bd.eionet.europa.eu/": "European Topic Centre on Biological Diversity (ETC/BD)",
    "http://uls.eionet.europa.eu": "European Topic Centre on Urban, Land and Soil Systems (ETC-ULS)",
    "https://www.eionet.europa.eu/etcs/etc-wmge": "European Topic Centre on Waste and Materials in a Green Economy (ETC/WMGE)",
    "http://www.etc.uma.es/index.php?lang=en": "European Topic Centre - Universidad de Málaga (ETC-UMA)",
    "http://europa.eu/index_en.htm": "European Union",
    "https://www.easa.europa.eu/en": "European Union Aviation Safety Agency (EASA)",
    "http://www.eureau.org": "European Union of National Associations of Water Suppliers and Waste Water Services",
    "http://www.euroreg.uw.edu.pl/en": "Euroreg",
    "http://www.eurosif.org/": "European Sustainable Investment Forum (Eurosif)",
    "http://www.fao.org/home/en/": "Faostat",
    "http://www.umweltbundesamt.at/en": "Federal Environment Agency - Austria",
    "https://www.umweltbundesamt.de/": "Federal Environmental Agency (UBA)",
    "http://www.bmu.de/english/aktuell/4152.php": "Federal Ministry for the Environment, Nature Conservation and Nuclear Safety and Federal Environment Agency",
    "https://www.bfs.admin.ch/bfs/en/home.html": "Federal Office for Statistics (FSO)",
    "https://www.fgg-weser.de/": "FGG Weser",
    "http://www.ymparisto.fi": "Finnish Environment Institute (SYKE)",
    "http://fmi.fi/en/index.html": "Finnish Meteorological Institute (FMI)",
    "http://en.ilmatieteenlaitos.fi/home": "Ilmatieteen laitos - Finnish Meteorological Institute (FMI)",
    "http://ec.europa.eu/dgs/fisheries/missn_en.htm": "Fisheries Directorate-General",
    "http://en.vmm.be/": "Flemish Environment Agency (VVM)",
    "https://www.cmcc.it/": "Fondazione Centro Euro-Mediterraneo sui Cambiamenti Climatici (CMCC Foundation)",
    "http://www.fapri.org/": "Food and Agricultural Policy Research Institute",
    "https://ic.fsc.org/": "Forest Stewardship Council",
    "http://www.forst.tu-muenchen.de/htdocs/fakul_en.php": "Forst TU-Muenchen",
    "http://www.blueflag.global": "Foundation for Environmental Education",
    "http://www.fu-berlin.de/en/index.html": "Freie Universität Berlin",
    "http://www.ifremer.fr/anglais": "French institute for marine research (IFREMER)",
    "http://www.international.inra.fr": "French National Institude for Agricultural Research (INRA)",
    "http://ne-friend.bafg.de": "Flow Regimes from International Experimental and Network Data (FRIEND Network)",
    "http://www.frost.com": "Frost & Sullivan",
    "https://www.fuelseurope.eu/": "FuelsEurope",
    "http://obrasocial.caixacatalunya.es/osocial/redirect.html?link=http://obrasocial.caixacatalunya.es/CDA/ObraSocial/Home/0,3423,3x0y,00.html": "Fundacio Caixa Catalunya",
    "http://armaag.gda.pl/": "Fundacja Armaag",
    "http://www.future-cities.eu/": "Future Cities - urban networks to face climate change",
    "http://www.fva-bw.de/indexjs.html?http://www.fva-bw.de/fva/fva.en.html": "FVA - The Forest Research Institute Baden-Wuerttemberg",
    "http://www.gencat.cat/index_eng.htm": "Generalitat de Catalunya",
    "http://www.cma.gva.es/web/indice.aspx?nodo=15&idioma=C": "Generalitat Valenciana",
    "http://geonetwork-opensource.org/": "Geo network - open source",
    "http://www.gim.be": "Geographic Information Management (GIM)",
    "https://www.geota.pt/": "GEOTA",
    "http://www.geoville.com": "GeoVille",
    "http://www.gibraltarairquality.gi/": "Gibraltar",
    "http://www.gisat.cz/content/cz": "GISAT",
    "http://www.footprintnetwork.org/en/index.php/GFN/": "Global Footprint Network",
    "http://www.gloria.ac.at/": "GLobal Observation Research Initiative in Alpine environments (GLORIA)",
    "https://www.globalreporting.org": "Global Reporting Initiative",
    "http://www.bafg.de/GRDC/EN/Home/homepage__node.html": "Global Runoff Data Centre (GRDC)",
    "https://www.gloh2o.org": "GloH2O",
    "http://www.aragon.es/": "Gobierno de Aragon, Spain",
    "http://www.giss.nasa.gov": "Goddard Institute for Space Studies (NASA)",
    "https://www.government.nl/": "Government of the Netherlands",
    "http://www.regierung.li/index.php?id=485": "Government of the Principality of Liechtenstein",
    "http://portal.tugraz.at/portal/page/portal/TU_Graz": "Graz University of Technology (TU Graz)",
    "http://www.alterra.wur.nl/UK/Home.htm": "Green World Research",
    "http://www.gmes-forest.info/index.htm": "GSE Forest Monitoring",
    "https://www.metoffice/": "To be deleted",
    "https://www.healthdata.org/": "Healthdata",
    "http://www.hcmr.gr": "Hellenic Centre for Marine Research (HCMR)",
    "http://www.helmholtz.de/en/helmholtz_centres/zentrum/detailansicht/helmholtz_centre_for_environmental_research_ufz/": "Helmholtz Centre for Environmental Research (UFZ)",
    "http://www.ufz.de/": "Helmholtz zentrum für ummeltforschung UFZ",
    "http://www.hsy.fi/en/Pages/Default.aspx": "Helsingin seudun ympäristöpalvelut - Helsinki Region Environmental Services Authority",
    "http://www.zamg.ac.at/histalp/index.html": "Historical instrumental climatological surface time series of the greater alpine region (HISTALP project)",
    "http://www.hmrc.gov.uk": "HM Revenue and Customs",
    "http://unfccc.int/national_reports/items/1408.php": "http://unfccc.int/national_reports/items/1408.php",
    "http://www.asecap.com/english/index.html": "European Association of Tolled Motorways, Bridges and Tunnel Concessionaires (ASECAP)",
    "http://www.bgs.ac.uk": "British Geological Survey (BGS)",
    "http://www.ebcc.info/index.php": "Entity to delete",
    "http://www.fapri.iastate.edu/": "Food and Agricultural Policy Research Institute (FAPRI)",
    "http://gains.iiasa.ac.at/models/": "Greenhouse Gas and Air Pollution Interactions and Synergies (GAINS)",
    "http://www.usf.uni-kassel.de/cesr/index.php?option=com_morefiles&Itemid=149&path=/dokumente/kwws/5": "http://www.usf.uni-kassel.de/cesr/index.php?option=com_morefiles&Itemid=149&path=/dokumente/kwws/5",
    "http://www.wbcsd.org/web/publications/mobility/smp-model-document.pdf": "Entity to delete",
    "https://www.hu-berlin.de/en": "Humboldt-Universität zu Berlin",
    "http://www.hu-berlin.de/": "Humboldt-University",
    "http://oki.antsz.hu/": "Hungarian Aerobiological Network (HAN)",
    "http://www.ktm.hu": "Hungarian Ministry for Environmental Protection",
    "http://www.hydrology-and-earth-system-sciences.net/index.html": "Hydrology and Earth System Sciences (HESS)",
    "http://icdc.zmaw.de/icdc.html?&L=1": "Integrated Climate Data Centre (ICDC)",
    "http://www.icp-forests.org": "ICP Forests",
    "https://www.iea.org/": "International Energy Agency (IEA)",
    "http://www.ifuplan.de/seiten_eng/institute/we_us_original.html": "Institute for Environmental Planning and Spatial Development (IFUPLAN)",
    "http://imbie.org/": "IMBIE",
    "http://impact2c.hzg.de/": "IMPACT2C",
    "http://webpubs.eea.europa.eu/content/irena/index.htm": "Indicator reporting on the integration of environmental concerns into agricultural policy",
    "http://www.ineris.fr/": "INERIS",
    "http://www.institut-montagne.org/index.php": "Institut de la montagne",
    "http://www.invs.sante.fr": "Institut de Veille Sanitaire (INVS)",
    "http://wwz.ifremer.fr": "Institut français de recherche pour l'exploitation de la mer (IFREMER)",
    "http://www.ifeu.de/english/index.php?seite=startseite": "Institute for Energy and Environmental Research (IFEU)",
    "http://www.ieep.eu/": "Institute for European Environmental Policy (IEEP)",
    "http://www.healthdata.org/": "Institute for Health Metrics and Evaluation (IHME)",
    "http://imk-ifu.fzk.de/": "Institute for Meteorology and Climate Research Atmospheric Environmental Research (IMK-IFU)",
    "http://www.tu-dresden.de/ipg/hometpg.html": "Institute for Planetary Geodesy",
    "https://go.itdp.org/display/live/Home": "Institute for Transportation and Development Policy (ITDP)",
    "http://www.bfafh.de/indexe.htm": "Institute for World Forestry",
    "http://www.isac.cnr.it/en": "Institute of Atmospheric Sciences and Climate",
    "http://www.gws-os.com/de/content/view/83/72/": "Institute of Economic Structures Research (GWS)",
    "https://ec.europa.eu/jrc/en/about/ies": "Institute of Environment and Sustainability (IES)",
    "http://www.fomi.hu/honlap/angol/Default.htm": "Institute of Geodesy, Cartography and Remote Sensing",
    "http://www.hydro.tuwien.ac.at/": "Institute of Hydraulic Engineering, TU Wien",
    "http://uke.sav.sk/index.php?lang=en": "Institute of Landscape Ecology, Slovak Academy of Sciences",
    "http://www.imr.no/english/main": "Institute of Marine Research, Norway",
    "http://www.univie.ac.at/?L=2": "Institute of Mountain Research (IGF) of the Austrian Academy of Sciences c/o University of Vienna",
    "http://www.instat.gov.al/": "Albanian Institute of Statistics (INSTAT)",
    "http://www.mn.uio.no/geo/": "Institutt for geofag (UiO)",
    "http://www.insuranceeurope.eu/": "Insurance Europe",
    "http://www.interact-eu.net/": "Interact",
    "https://www.theice.com/index": "Intercontinental Exchange Inc (ICE)",
    "http://www.ipcc.ch": "Intergovernmental Panel on Climate Change (IPCC)",
    "http://www.ikar-cisa.org": "International Commision for Alpine Rescue",
    "https://ieeexplore.ieee.org/Xplore/home.jsp": "International Conference on Ecological Vehicles and Renewable Energies (EVER) - IEEE Xplore",
    "http://www.ices.dk": "International Council for the Exploration of the Sea (ICES)",
    "http://www.theicct.org": "International Council on Clean Transportation",
    "http://iea.uoregon.edu/page.php?file=home.htm&query=static": "International Environmental Agreements",
    "http://www.fertilizer.org/ifa/": "International Fertilizer Industry Association (IFA)",
    "http://www.ifpri.org/": "International Food Policy Research Institute (IFPRI)",
    "http://www.igbp.net/": "International Geosphere-Biosphere Programme",
    "http://www.igsoc.org/": "International glaciological society (IGS)",
    "http://www.ihdp.unu.edu/pages/?p=about": "International Human Dimensions Programme on Global Environmental Change",
    "http://webworld.unesco.org/water/ihp": "International Hydrological Programme",
    "http://www.iinas.org/": "International Institute for Sustainability Analysis and Strategy (IINAS)",
    "http://www.ij-healthgeographics.com": "International journal of health geographics",
    "http://ipa.arcticportal.org/": "International Permafrost Association",
    "http://iri.columbia.edu": "International Research Institute for Climate Prediction",
    "http://journals.lww.com/epidem/pages/default.aspx": "International Society for Environmental Epidemiology",
    "http://www.isric.org": "International Soil Reference and Information Centre",
    "http://www.uic.org": "International Union of Railways (UIC)",
    "http://www.internationaltransportforum.org": "International Transport Forum (ITF)",
    "http://www.cisstat.com/eng/macro0.htm": "Interstate Statistical Committee of the Commonwealth of Independent States (CIS)",
    "http://www.cabi.org": "Invasive Species Compendium - CABI",
    "http://www.issg.org/index.html": "Invasive Species Specialist Group (ISSG)",
    "http://www.irceline.be/": "IRCEL - CELINE",
    "http://www.islandpress.com": "Island Press",
    "http://www.isprambiente.it/site/en-GB/default.html": "ISPRA",
    "http://issar.cenia.cz/issar/page.php?id=87": "ISSaR",
    "http://www.gobiernodecanarias.org/istac/istac/": "ISTAC: Instituto Canario de Estadística",
    "http://gnoo.bo.ingv.it": "Istituto Nazionale di Geofisica e Vulcanologia",
    "http://www.ivl.se/english/startpage.4.4a08c3cb1291c3aa80e80001374.html": "IVL - Swedish Environmental Research Institute",
    "http://www.jamstec.go.jp/": "Japan Agency for Marine-Earth Science and Technology",
    "https://www.jma.go.jp/jma/indexe.html": "Japan Meteorological Agency (JMA)",
    "http://www.jpl.nasa.gov": "Jet Propulsion Laboratory",
    "http://jncc.defra.gov.uk": "Joint Nature Conservation Committee (JNCC)",
    "http://agupubs.onlinelibrary.wiley.com/agu/jgr/journal/10.1002/(ISSN)2169-8996/": "Journal of geophysical research: Athmosfere",
    "http://www.chj.es/es-es/Organismo/Paginas/Organismo.aspx": "Jucar River Basin Authority",
    "http://www.jkl.fi/ymparisto/ymparistonsuojelupalvelut/ilmansuojelu/ilmantarkkailu": "Jyväskylä",
    "https://www.imk-tro.kit.edu/": "Karlsruhe Institute of technology",
    "http://www.uni-kassel.de": "Kassel University",
    "https://knoema.com/": "KNOEMA",
    "http://www.hofor.dk/fjernvarme": "Københavns Energi",
    "http://www.kuopio.fi/web/english": "Kuopio",
    "http://www.kvvm.hu/olm/info.php?lang=hu": "KVVM - Hungarian Air Quality Network",
    "http://www.kystverket.no/": "Kystverket",
    "http://lgge.osug.fr/?lang=en": "Laboratorie de Glaciologie et Géophysique de l'Environnement (LGGE)",
    "http://www.lahti.fi/www/cms.nsf": "Lahti",
    "https://www.lancetcountdown.org/europe/": "Lancet Countdown in Europe",
    "http://www.edc.uri.edu/lme": "Large Marine Ecosystem (LME)",
    "http://www3.meteo.lv/public/index.html": "Latvijas Vides, ģeoloģijas un meteoroloģijas centrs",
    "https://www.llnl.gov/": "Lawrence Livermore National Laboratory (LLNL)",
    "http://www.learnstuff.com/": "LearnStuff",
    "http://www.ioer.de/1/home/": "Leibniz Institute of Ecological Urban and Regional Development (IOER)",
    "http://www.leidenuniv.nl": "Leiden University",
    "http://www.lshtm.ac.uk/": "London School of Hygiene and Tropical Medicine",
    "https://www.nateko.lu.se/research/remote-sensing-and-earth-observation/lund-earth-observation-research-group/vegetation-phenology-0": "Lund University",
    "http://www.mepa.org.mt/air": "Malta Environment and Planning Authority (MEPA)",
    "https://marinelitterlab.eu/": "Maluca research lab (University of Cádiz, Biology department)",
    "https://www.muni.cz/": "Masaryk University",
    "http://www.mpimet.mpg.de/en/home.html": "Max Planck Institute for Meteorology",
    "http://mayors-adapt.eu/": "Mayors Adapt",
    "http://www.medcruise.com/": "MedCruise",
    "http://www.moon-oceanforecasting.eu/index.php?option=com_frontpage&Itemid=1": "Mediterranean Observational Oceanography Network (MOON)",
    "http://www.asecap.com": "Member states",
    "http://hadobs.metoffice.com": "Met Office Hadley Centre observations datasets",
    "http://www.msceast.org": "Meteorological Synthesizing Centre-East (MSC-E)",
    "http://www.metropolis.org": "Metropolis",
    "https://agriculture.gouv.fr/": "Ministère de l’Agriculture et de la Souveraineté Alimentaire - DGAL",
    "http://www.foresteurope.org/": "Forest Europe",
    "http://www.magrama.gob.es/es/": "Ministry of Agriculture, Alimentation and Environment (Magrama)",
    "http://www.moepp.gov.mk/default-en.asp": "Ministry of Environment and Physical Planning (MoEPP)",
    "http://www.minenv.gr/#": "Ministry of Environment, Energy and Climate Change, Greece.",
    "http://www.mzopu.hr/index.htm": "Ministry of Environmental Protection, Physical Planning and Construction",
    "https://eng.atvinnuvegaraduneyti.is/": "Ministry of Industries and innovation",
    "http://www.mppt.gov.al/": "Ministry of Public Works and Transport of Albania (MPPT)",
    "https://www.msit.gov.pl/": "Ministry of Sport and Tourism of the Republic of Poland",
    "https://www.eurocontrol.int/": "Eurocontrol",
    "http://www.cryoclim.net/cryoclim/index.php/HOME": "Monitoring Climate Change in the Cryosphere (CryoClim)",
    "http://www.msu.ru/en": "Moscow State University",
    "http://link.springer.com/article/10.1007%2Fs10584-016-1661-x": "Multi-hazard assessment in Europe under climate change",
    "https://www.mdpi.com/": "Multidisciplinary Digital Publishing Institute (MDPI)",
    "http://www.munichre.com": "Munich Re",
    "http://www.wien.gv.at/english/environment/protection/": "Municipal Department 22 - Environmental Protection in Vienna (MA 22)",
    "http://www.plovdiv.bg/#": "Municipality of Plovdiv",
    "http://www.aplinka.vilnius.lt/lt/": "Municipality of Vilnius",
    "http://www.bhas.ba": "Agency for Statistics of Bosnia and Herzegovina (BHAS)",
    "http://atm.wff.nasa.gov": "NASA",
    "http://www.pnas.org/": "National Academy of Sciences of the United States of America (PNAS)",
    "http://www.dmu.dk/International": "Nationalt Center for Miljø og Energi - National Environmental Research Institute (NERI)",
    "http://gnoo.bo.ingv.it/index.php?lang=en": "National Group for Operational Oceanography (GNOO)",
    "http://www.szu.cz/English/english.htm": "National Institute of Public Health (NIPH), Czech Republic",
    "http://www.cnr.it/sitocnr/Englishversion/Englishversion.html": "National Research Council (CNR)",
    "http://nsidc.org": "National Snow and Ice Data Center (NSIDC)",
    "http://www.naturalearthdata.com/": "Natural Earth",
    "http://www.natural-hazards-and-earth-system-sciences.net/home.html": "Natural Hazards and Earth System Sciences (NHESS)",
    "http://www.nhm.ac.uk/": "Natural History Museum (NHM)",
    "https://www.nature.com/": "Nature Research",
    "http://www.naturescalendar.org.uk": "Nature's Calendar",
    "http://www.netcen.co.uk": "NETCEN",
    "http://www.pbl.nl/en/": "Netherlands Environmental Assessment Agency (PBL)",
    "http://www.medpan.org/home": "Network of Marine Protected Area Managers in the Mediterranean",
    "http://niva-dk.dk/": "NIVA Denmark",
    "http://www.noaa.gov/": "National Oceanic and Atmospheric Administration (NOAA)",
    "https://www.ncdc.noaa.gov/": "NOAA's National Centers for Environmental Information (NCEI)",
    "http://www.nord-stream.com": "Nord Stream",
    "http://www.nordic-ilibrary.org/": "Nordic iLibrary",
    "http://www.nordregio.se/about": "Nordregio",
    "http://www.luftkvalitet.info/home.aspx": "Norsk Institutt for luftforskning",
    "https://www.ngi.no/eng/": "Norwegian Geotechnical Institute (NGI)",
    "http://www.nilu.no": "Norwegian Institute for Air Research (NILU)",
    "http://www.nina.no": "Norwegian Institute for Nature Research (NINA)",
    "http://www.niva.no/engelsk/welcome.htm": "Norwegian Institute for Water Research (NIVA)",
    "http://www.nve.no": "Norwegian Water Resources and Energy Directorate (NVE)",
    "http://www.ornl.gov/": "Oak Ridge National Laboratory (ORNL)",
    "http://met.no/English/": "Norwegian Meteorological Institute",
    "http://www.osi-saf.org/": "Ocean and Sea Ice Satellite Application Facility (OSI SAF)",
    "http://www.myocean.eu/": "Ocean Monitoring and Forecasting (MyOcean)",
    "http://www.odyssee-indicators.org": "ODYSSEE - Energy Efficiency Indicators in Europe",
    "https://obr.uk/": "Office for Budget Responsibility (OBR)",
    "http://www.ons.gov.uk/ons/index.html": "Office for National Statistics (ONS)",
    "http://www.diba.cat/en/web/mediambient/presentacio#1": "Oficina de Canvi Climàtic i Sostenibilitat",
    "http://www.oeko.de/en/": "Öko-Institut e.V.",
    "http://www.openstreetmap.org": "OpenStreetMap",
    "https://blog.openstreetmap.org": "OpenStreetMap Foundation",
    "http://www.organic.aber.ac.uk/index.shtml": "Organic Centre Wales",
    "http://hdr.undp.org/en/data": "United Nations Development Programme (UNDP)",
    "http://www.os.is/page/english": "ORKUSTOFNUN - National Energy Authority",
    "http://www.ospar.org": "OSPAR Commision",
    "http://www.ostluft.ch/": "OSTLUFT - Liechtenstein",
    "https://ourworldindata.org/": "Our World in Data",
    "http://www.cigogne-loutre.com": "Parc des cigognes et les loutres",
    "http://www.pbworks.com/index.html": "PBworks, Inc.",
    "http://www.permos.ch": "Permafrost Monitoring Switzerland (PERMOS)",
    "http://www.psmsl.org/": "Permanent service for mean sea level (PSMSL)",
    "http://planbleu.org/en": "Plan Bleu",
    "https://plasticseurope.org/": "Plastics Europe",
    "http://journals.plos.org/plosntds/": "PLOS Neglected Tropical Diseases",
    "http://www.plosone.org/": "PLoS ONE",
    "http://www.pml.ac.uk": "Plymouth Marine Laboratory (PLM)",
    "https://www.pocitovemapy.cz": "Pocitovemapy",
    "http://www.pointcarbon.com": "Point Carbon",
    "http://psc.apl.uw.edu/": "Polar Science Center",
    "http://www.polimi.it": "Politecnico di Milano (ITA)",
    "http://www.portbooker.com/en/": "Portbooker",
    "http://www.pik-potsdam.de/": "Potsdam Institute for Climate Impact Research (PIK)",
    "http://www.ozean-klima.de/": "Potsdam Institute for Climate (PIK)",
    "http://www.prognos.com": "Prognos",
    "http://www.pefc.org/": "Programme for the Endorsement of Forest Certification (PEFC)",
    "https://op.europa.eu/en/home": "Publication Office of the European Union",
    "https://ramses-cities.eu/results": "RAMSES H2020 project",
    "https://www.refinitiv.com": "Refinitive",
    "http://www.carm.es/cmaot/calidadaire/portal/": "Region de Murcia",
    "http://www.rac-spa.org/": "Regional Activity Center for Specially Protected Areas",
    "http://www.rec.org/": "Regional Environmental Centre",
    "https://www.sciencedirect.com/science/article/pii/S1364032122001356": "Renewable and Sustainable Energy Reviews. Volume 160 - Elsevier",
    "http://www.rivm.nl": "Research for Man and Environment (RIVM)",
    "http://www.inbo.be/": "Research Institute for Nature and Forest (INBO)",
    "https://www.fibl.org/": "Research Institute of Organic Agriculture (FIBL)",
    "https://resin-cities.eu/": "RESIN project",
    "http://www.ricardo-aea.com": "Ricardo-AEA",
    "http://www.rijkswaterstaat.nl": "Rijkswaterstaat",
    "https://www.rksk.dk/": "Ringkobing-Skjern Kommune",
    "http://www.risklayer.com/en/": "RiskLayer",
    "https://riverwatch.eu/": "Riverwatch",
    "http://www.rmets.org/index.php": "Royal Meteorological Society",
    "http://www.knmi.nl": "Royal Netherlands Meteorological Institute (KNMI)",
    "http://www.rspb.org.uk": "Royal Society for the Protection of Birds",
    "https://www.rsc.org/": "Royal Society of Chemistry",
    "http://thsk.gov.tr/tr/index.php": "RSHC-Turkey",
    "https://journals.sagepub.com/": "SAGE journals",
    "http://stecf.jrc.ec.europa.eu/reports": "Scientific, Technical and Economic Committee for Fisheries (STECF)",
    "http://scp-hat.lifecycleinitiative.org/": "SCP HOTSPOT ANALYSIS",
    "http://sio.ucsd.edu": "Scripps Institution of Oceanography (SIO)",
    "http://www.seaaroundus.org": "Sea Around Us Project",
    "http://seaaroundus.org": "Sea around us project",
    "http://www.seamlessassociation.org/": "Seamless association",
    "http://www.stadtentwicklung.berlin.de/index_en.shtml": "Senate Department for Urban Development and Housing",
    "http://www.senecabtc.com": "Seneca",
    "http://www.sepa.gov.rs/index.php": "Serbian Environmental Protection Agency (SEPA)",
    "http://www.sgu.se/sgu/en": "SGU - Geological Survey of Sweden",
    "http://www.sinanet.isprambiente.it/it": "SINAnet - sistema Informativo Nazionale Ambientale",
    "http://www.shmu.sk/sk/?page=1": "Slovak Hydrometeorological Institute (SHMI)",
    "http://www.sazu.si": "Slovenian Academy of Sciences and Arts (SAZU)",
    "http://www.arso.gov.si/": "Slovenian Environment Agency",
    "http://www.snclavalin.com/index.php?lang=en": "SNC-Lavalin",
    "http://www.socialstyrelsen.se": "Socialstyrelsen",
    "http://space4environment.com": "Space4environment",
    "http://www.anfac.com/portada.action": "Spanish Association of Automobile and Truck Manufacturers (ANFAC)",
    "http://www.feapdt.es/en/": "Spanish Federation of Marinas and Touristic Associations (FEAPDT)",
    "http://www.springer.com/gp/": "Springer International Publishing AG",
    "http://www.stat.gov.mk/english/glavna_eng.asp": "State Statistical Office, North Macedonia",
    "https://www.statista.com": "Statista - The portal for statistics",
    "http://epp.eurostat.ec.europa.eu": "Statistical Office of the European Union (Eurostat)",
    "http://webrzs.stat.gov.rs/axd/en/index.php": "Statistical Office of the Republic of Serbia",
    "http://www.statbank.dk": "Statistics Denmark",
    "http://www.cbs.nl/en-GB/default.htm": "Statistics Netherlands",
    "http://www.destatis.de/jetspeed/portal/cms/": "Statistisches Bundesamt Deutschland (Destatis)",
    "http://www.su.se": "Stockholm University",
    "http://www.stoxx.com/index.html": "STOXX",
    "http://www.isemar.asso.fr/english/index.htm": "Superior Institute of Maritime Economy",
    "http://internat.environ.se": "Swedish Enviromental Protection Agency",
    "http://www.naturvardsverket.se/en/": "Swedish Environmental Protection Agency",
    "http://www.smhi.se": "Swedish meteorological and hydrologiska insitute (SMHI)",
    "http://www.slu.se/en/": "Swedish university of agricultural sciences (SLU)",
    "http://www.wsl.ch/index_EN": "Swiss Federal Institute for Forest, Snow and Landscape Research (WSL)",
    "http://www.bafu.admin.ch/?lang=en": "Swiss Federal Office for the Environment (FOEN)",
    "http://www.vuv.cz/en": "T. G. Masaryk Water Research Institute, p.r.i.",
    "http://www.tcvode.si/": "TC Vode",
    "http://www.vttresearch.com/": "Technical Research Centre of Finland (VTT)",
    "http://www.tu-muenchen.de": "Technical University of Munich (TUM)",
    "http://www.raumplanung.tu-dortmund.de/irpud/en/home/": "Technische Universität Dortmund, Institute of Spatial Planning (IRPUD)",
    "http://www.tu-dresden.de": "Technische Universitat Dresden (TUD)",
    "http://www.tele-mart.com/": "Tele Mart",
    "http://www.itameriportaali.fi/fi_FI/": "Baltic sea portal",
    "http://www.conference-board.org/": "The Conference Board",
    "http://www.geology.cz": "The Czech Geological Survey",
    "http://british-dragonflies.org.uk": "Dragonfly Society of the British Isles (BDS)",
    "http://www.vlinderstichting.nl": "Dutch Butterfly Conservation",
    "http://www.ust.is/": "The Environment Agency of Iceland",
    "http://sia.eionet.europa.eu": "European Topic Centre for Spatial information and Analysis (ETC/SIA)",
    "http://air-climate.eionet.europa.eu": "European Topic Centre on Air and Climate Change (ETC/ACC)",
    "http://terrestrial.eionet.europa.eu": "The European Topic Centre on Land Use and Spatial Information",
    "http://scp.eionet.europa.eu/": "EUROPEAN TOPIC CENTRE ON SUSTAINABLE CONSUMPTION AND PRODUCTION (ETC/SCP)",
    "https://www.eionet.europa.eu/etcs/etc-icm": "European Topic Centre on Inland, Coastal and Marine waters (ETC/ICM)",
    "http://www.ewea.org/": "The European wind energy association (EWEA)",
    "http://www.tfi.org/": "The Fertilizer Institute, Washington DC (TFI)",
    "http://www.fao.org/": "Food and Agriculture Organization of the United Nations (FAO)",
    "http://www.fe.ethz.ch/index_EN": "Forest Ecology Group at the Swiss Federal Institute of Technology in Zurich (ETH)",
    "http://www.helcom.fi": "Helsinki Commission (HELCOM)",
    "http://www.iccat.es": "International Commission for the Conservation of Atlantic Tunas (ICCAT)",
    "http://www.iiasa.ac.at": "International Institute for Applied Systems Analysis (IIASA)",
    "http://www.imf.org/external/": "International Monetary Fund (IMF)",
    "http://www.itopf.com": "International Tanker Owners Pollution Federation Limited (ITOPF)",
    "http://www.iucn.org/home": "International Union for Conservation of Nature (IUCN)",
    "https://ec.europa.eu/info/departments/joint-research-centre_en": "Joint Research Centre (JRC)",
    "http://hahana.soest.hawaii.edu/index.html": "The Laboratory for Microbial Oceanography (Hawaii)",
    "http://lat.eng.auth.gr/": "The Laboratory for Thermodynamics of the Aristoteles University of Thessaloniki (LAT/AuTh)",
    "http://www.parc-marin-iroise.com/": "The management council of the Iroise Marine Nature Park",
    "http://www.ypeka.gr/Default.aspx?tabid=37&locale=en-US&language=el-GR": "The Ministry of Environment, Energy and Climate Change",
    "http://www.bafu.admin.ch/luft/": "Entity to delete",
    "http://www.rivm.nl/en": "Rijksinstituut voor Volksgezondheid en Milieu - National Institute for Public Health and the Environment (RIVM)",
    "http://www.ntua.gr": "National Technical University of Athens (NTUA)",
    "http://www.nobanis.org": "North European and Baltic Network on Invasive Alien species (NOBANIS)",
    "http://www.oecd.org": "Organisation for Economic Co-operation and Development (OECD)",
    "http://www.reabic.net/": "The Regional Euro-Asian Biological Invasions Centre (REABIC)",
    "https://www.rockefellerfoundation.org": "The Rockefeller Foundation",
    "https://www.knmi.nl/home": "The Royal Netherlands Meteorological Institute (KNMI)",
    "http://royalsociety.org": "The Royal Society",
    "http://climate.rutgers.edu/snowcover/": "Rutgers University Global Snow Lab",
    "http://www.sahfos.org": "Sir Alister Hardy Foundation for Ocean Science (SAHFOS)",
    "http://seri.at/": "The Sustainable Europe Research Institute (SERI)",
    "http://www.ucte.org/": "The Union for the Co-ordination of Transmission of Electricity (UCTE)",
    "http://www.un.org/esa/desa.htm": "United Nations Department of Economic and Social Affairs (UN DESA)",
    "http://www.unece.org/env": "United Nations Economic Commission for Europe (UNECE)",
    "http://www.unece.org/forests/welcome.html": "United Nations Economic Commission for Europe (Forest Resources Assessment)",
    "http://www.unep.org": "United Nations Environment Programme (UNEP)",
    "http://www.unep.org/About/": "The United Nations Environment Programme (UNEP)",
    "http://www.ed.ac.uk/home": "The University of Edinburgh, Scotland",
    "http://www.aber.ac.uk": "University of Wales, Aberystwyth",
    "http://www.vcacarfueldata.org.uk": "The Vehicle Certification Agency",
    "http://www.ices.dk/community/groups/Pages/WGBOSV.aspx": "The Working Group on Ballast and Other Ship Vectors (WGBOSV)",
    "http://www.ices.dk/community/groups/Pages/WGITMO.aspx": "The Working Group on Introduction and Transfers of Marine Organisms (WGITMO)",
    "http://www.worldbank.org": "The World Bank",
    "http://www.iucn.org": "World Conservation Union",
    "http://www.worldenergy.org/": "The World Energy Council (WEC)",
    "https://www.thuenen.de/en/": "Thünen Institute",
    "https://www.tno.nl/en/": "Netherlands Organisation for Applied Scientific Research",
    "http://www.telecom.gov.sk/index/index.php?lang=en": "Ministry of transport and construction of the Slovak Republic",
    "https://tracasa.es/": "Tracasa",
    "https://telraam.net/": "Transport and Mobility Leuven,Telraam",
    "http://www.tfl.gov.uk/": "Transport for London (TfL)",
    "https://www.sciencedirect.com/science/article/pii/S0965856421002627": "Transportation Research Part A: Policy and Practice. Volume 154  - Elsevier",
    "https://www.sciencedirect.com/science/article/pii/S0965856422000143": "Transportation Research Part A: Policy and Practice. Volume158 - Elsevier",
    "http://www.tremove.org/": "TREMOVE model",
    "http://acm.eionet.europa.eu/databases/TRENDS/index_html": "TRENDS model",
    "http://trinomics.eu/": "Trionomics",
    "http://www.turku.fi/Public/default.aspx?nodeid=12078&culture=en-US&contentlan=2": "Turku Environmental Protection Office",
    "http://www.fueleconomy.gov/": "U.S. Environmental Protection Agency",
    "http://www.usgs.gov/": "U.S. Geological Survey (USGS)",
    "http://www.uitp.org": "UITP - International Association of Public Transport",
    "http://www.ukcip.org.uk": "UK Climate Impacts Programme",
    "http://www.dft.gov.uk": "UK Department for Transport (DFT)",
    "https://www.metoffice.gov.uk/": "Met Office United Kingdom",
    "http://uk-air.defra.gov.uk/": "UK National Air Quality Information Archive",
    "http://www.nerc.ac.uk/index.asp?cookieConsent=A": "Natural Environment Research Council (NERC)",
    "http://www.env-it.de/umweltbundesamt/luftdaten/index.html?setLanguage=en": "Umwelt Bundes Amt (UBA)",
    "https://comtrade.un.org/": "UN Comtrade",
    "https://www.unenvironment.org": "UN environment programme (IRP)",
    "http://www.unece.org/info/ece-homepage.html": "United Nations Economic Commission for Europe (UNECE)",
    "http://www.grida.no": "UNEP/GRID-Arendal",
    "http://www.grid.unep.ch": "UNEP GRID Geneva",
    "http://www.gridw.pl": "UNEP GRID Warszawa",
    "http://ozone.unep.org/": "UNEP (Ozone Secretariat)",
    "http://www.unep.ch/roe": "UNEP - Regional Office for Europe",
    "http://www.unep-wcmc.org/index.html": "UNEP World Conservation Monitoring Centre",
    "http://www.un.org/": "United Nations (UN)",
    "http://www.unepmap.org/index.php": "United Nations Environment Programme / Mediterranean Action Plan (UNEP/MAP)",
    "http://www.unep-wcmc.org": "United Nations Environment Programme World Conservation Monitoring Centre",
    "http://www.unfccc.int": "United Nations Framework Convention on Climate Change (UNFCCC)",
    "http://www.unisdr.org": "United Nations Office for Disaster Risk Reduction, UNISDR",
    "http://unstats.un.org/unsd/methods/icp/gdp/gdp01_htm.htm": "United Nations Statistics Division (UNSTAT)",
    "http://www3.epa.gov/": "United States Environmental Protection Agency (EPA)",
    "http://www.upm.es/institucional": "Universidad Politecnica de Madrid",
    "http://www.unifi.it/": "Università degli Studi di Firenze",
    "http://www.uab.cat": "Universitat Autònoma de Barcelona (UAB)",
    "http://www.uni-siegen.de/": "Universität Siegen",
    "https://portail.umons.ac.be/en2/pages/default.aspx": "Universite de Mons",
    "http://www.uni-due.de/hydrobiology": "University Duisburg-Essen, Research Group",
    "http://www.au.dk": "University of Aarhus",
    "http://abdn.ac.uk": "University of Aberdeen",
    "http://www.uni-bayreuth.de/index.html": "University of Bayreuth",
    "http://www.unibe.ch/eng": "University of Bern",
    "http://iup.physik.uni-bremen.de/deu/": "University of Bremen",
    "http://www.eos.ubc.ca/": "University of British Columbia (UBC)",
    "http://cires.colorado.edu": "University of Colorado (CIRES)",
    "http://macroecology.ku.dk/": "University of Copenhagen",
    "http://www.uni-duisburg-essen.de/en/international.php": "University of Duisburg-Essen",
    "http://www.cru.uea.ac.uk": "University of East Anglia, Climate Research Unit",
    "http://www.uni-freiburg.de/": "University of Freiburg",
    "https://www.unige.ch/en/": "University of Geneva - Université de Genève",
    "http://www.dpes.gu.se/english/?languageId=100001&contentId=-1&disableRedirect=true&returnUrl=http://www.dpes.gu.se/": "University of Gothenburg",
    "http://www.rug.nl/corporate/index": "University of Groningen",
    "http://www.hawaii.edu/": "University of Hawaii",
    "http://cms.uni-kassel.de/": "University of Kassel",
    "http://www.wildlandresearch.org": "University of Leeds",
    "http://www.geographie.ulg.ac.be/index.php": "University of Liège (ULg)",
    "http://www.boku.ac.at/": "University of Natural Resources and Life Sciences, Vienna (BOKU)",
    "http://newcastle.edu.au": "University of Newcastle",
    "http://gain.org/": "University of Notre Dame, Notre Dame Global Adaptation Index (ND-GAIN)",
    "https://www.uio.no/": "University of Oslo",
    "http://www.reading.ac.uk": "University of Reading",
    "http://www.southampton.ac.uk/": "University of Southhampton",
    "http://www3.aegean.gr/aegean/en/intro_en.htm": "University of the Aegean",
    "https://www.utwente.nl/en/": "University of Twente",
    "http://www.virginia.edu": "University of Virginia (USA)",
    "http://www.york.ac.uk/biology/research/": "University of York",
    "http://www.unizar.es/": "University of Zaragoza",
    "http://www.geo.uzh.ch": "University of Zurich",
    "http://data.worldbank.org/": "World Development Indicators (WDI)",
    "http://www.example.com": "Unspecified",
    "http://www.usa.gov": "USA Government",
    "http://www.uu.nl/": "Utrecht University (UU)",
    "https://www.uantwerpen.be/nl/personeel/steven-vanpassel/": "Van Passel et al.",
    "http://www.verbund.com/at/de/": "Verbund AG",
    "http://www.materialflows.net/": "Vienna University of Economics and Business",
    "http://www.vims.edu/": "Virginia Institute of Marine Science",
    "https://vito.be/en": "VITO (Vlaamse Instelling voor Technologisch Onderzoek)",
    "https://www.wur.nl/en.htm": "Wageningen University and Research",
    "http://www.pps.wur.nl/UK/": "Wageningen University  (WUR)",
    "http://wokinfo.com/": "Web of Knowledge database",
    "https://wegcenter.uni-graz.at/en/": "Wegener Center for Climate and Global Change",
    "http://www.wetlands.org": "Wetlands International",
    "http://www.wikipedia.org/": "Wikipedia",
    "http://onlinelibrary.wiley.com/": "Wiley Online Library",
    "http://www.4coffshore.com": "4C Offshore",
    "http://www.wios.bialystok.pl/index.php?go=stanal": "WIOS Bialystok, Poland",
    "http://www.katowice.pios.gov.pl/": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS) Katowicach",
    "http://www.wios.lodz.pl/serwis/index.php?id=80": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS) Łódź",
    "http://www.wios.olsztyn.pl/": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS) Olsztyn",
    "http://www.opole.pios.gov.pl/": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS) Opole",
    "http://www.wios.szczecin.pl/bip/chapter_16156.asp": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS) Szczecin",
    "http://www.wios.bydgoszcz.pl/": "Wojewódzki Inspektorat Ochrony Środowiska w Bydgoszczy",
    "http://www.wios.rzeszow.pl/": "Wojewódzki Inspektorat Ochrony Środowiska w Rzeszowie",
    "http://www.wios.lublin.pl/tiki-custom_home.php": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS ) w Lublinie",
    "http://zgora.pios.gov.pl/wios/": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS ) w Zielonej Górze",
    "http://www.wroclaw.pios.gov.pl/index.php?id=wios": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS ) w Wrocławiu",
    "http://www.krakow.pios.gov.pl/index.php": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS ) w Krakowie",
    "http://www.wios.warszawa.pl/portal/pl/": "Wojewódzki Inspektorat Ochrony Środowiska (WIOS ) w Warszawie",
    "http://databank.worldbank.org/data/home.aspx": "World DataBank",
    "http://www.wdpa.org/Default.aspx": "World Database on Protected Areas",
    "https://www.weforum.org/": "World Economic Forum",
    "http://www.worldenergyoutlook.org/": "World Energy Outlook (WEO)",
    "http://www.wgms.ch": "World Glacier Monitoring Service (WGMS)",
    "http://www.who.int/en/": "World Health Organisation (WHO)",
    "http://www.euro.who.int": "World Health Organization Regional Office for Europe (WHO/Europe)",
    "http://www.wiod.org/new_site/home.htm": "World Input-Output Database (WIOD)",
    "http://www.wipo.int/portal/en/index.html": "World Intellectual Property Organization (WIPO)",
    "http://www.wmc.org.pl/": "World Mining Congress (WMC)",
    "http://www.wri.org": "World Resources Institute (WRI)",
    "http://www.worldclim.org/": "WorldClim - Global Climate Data",
    "http://www.worldmapper.org/index.html": "Worldmapper",
    "https://wrap.org.uk/": "WRAP",
    "http://www.world-tourism.org/": "World Tourism Organization (UNWTO)",
    "http://www.wupperinst.org/en/home/index.html": "Wuppertal  institute for climate, Environment and energy",
    "https://www.wwf.eu/": "WWF",
    "http://www.wwf.ru/eng": "WWF Central Asia Programme",
    "http://www.wwf.org.uk": "WWF UK",
    "http://www.mis.org.yu/index.php?lang=eng": "Young Researchers of Serbia",
    "http://zenat-tourismus.de/": "ZENAT (Zentrum für nachhaltigen Tourismus an der Hochschule für nachhaltige Entwicklung Eberswalde)",
    "https://zenodo.org/": "Zenodo",
    "https://www.zsl.org/": "Zoological Society of London (ZSL)",
}
